function Hd = highpass_iirfilter_df2transposed_3sos_indouble
%HIGHPASS_IIRFILTER_DF2TRANSPOSED_3SOS_INDOUBLE Returns a discrete-time filter object.

%
% MATLAB Code
% Generated by MATLAB(R) 7.12 and the DSP System Toolbox 8.0.
%
% Generated on: 14-Apr-2014 20:46:25
%

% Elliptic Highpass filter designed using FDESIGN.HIGHPASS.

% All frequency values are in Hz.
Fs = 8000;  % Sampling Frequency

Fstop = 1000;    % Stopband Frequency
Fpass = 1700;    % Passband Frequency
Astop = 60;      % Stopband Attenuation (dB)
Apass = 0.1;     % Passband Ripple (dB)
match = 'both';  % Band to match exactly

% Construct an FDESIGN object and call its ELLIP method.
h  = fdesign.highpass(Fstop, Fpass, Astop, Apass, Fs);
Hd = design(h, 'ellip', 'MatchExactly', match);
% Convert the filter to the Direct-Form II Transposed, SOS structure.
Hd = convert(Hd, 'df2tsos');
pnorm  = 'l1';    % Pth Norm
maxnum = 2;       % Maximum Numerator
numcon = 'None';  % Numerator Constraint
omode  = 'Wrap';  % Overflow Mode
svcon  = 'Unit';  % Scale Value Constraint

scale(Hd, pnorm, ...
    'MaxNumerator', maxnum, ...
    'NumeratorConstraint', numcon, ...
    'Overflowmode', omode, ...
    'ScaleValueConstraint', svcon, ...
    'SOSReorder', 'none');

% [EOF]
